import json
from datetime import datetime

message = None
social_posts_catalog_backup = dict()
files_log = dict()

social_posts_catalog = {
    1: {
        "user_id": 1001,
        "username": "dave_k",
        "text": "The sunrise this morning was absolutely breathtaking",
        "topic": "Technology",
        "classification": "neutral",
        "number_of_words": 7,
        "special_elements": 52,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 140,
        "no_of_comments": 31,
        "no_of_shares": 14,
        "processed": True,
    },
    2: {
        "user_id": 1002,
        "username": "dave_k",
        "text": "The new policy announcement is confusing, honestly.",
        "topic": "Music",
        "classification": "neutral",
        "number_of_words": 7,
        "special_elements": 51,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 456,
        "no_of_comments": 69,
        "no_of_shares": 5,
        "processed": True,
    },
    3: {
        "user_id": 1003,
        "username": "carol_w",
        "text": "So proud of my team for this achievement #Teamwork 😀 😂",
        "topic": "Sports",
        "classification": "pos",
        "number_of_words": 11,
        "special_elements": 54,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Teamwork"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["😀", "😂"],
        "no_of_likes": 258,
        "no_of_comments": 77,
        "no_of_shares": 1,
        "processed": True,
    },
    4: {
        "user_id": 1004,
        "username": "grace_l",
        "text": "Why is the internet so slow today ugh",
        "topic": "Gaming",
        "classification": "neutral",
        "number_of_words": 8,
        "special_elements": 37,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 359,
        "no_of_comments": 69,
        "no_of_shares": 26,
        "processed": True,
    },
    5: {
        "user_id": 1005,
        "username": "olivia_u",
        "text": "Feeling great after my morning workout #Health #Fitness",
        "topic": "Movies",
        "classification": "neg",
        "number_of_words": 8,
        "special_elements": 55,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Health", "#Fitness"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 414,
        "no_of_comments": 0,
        "no_of_shares": 48,
        "processed": True,
    },
    6: {
        "user_id": 1006,
        "username": "eve_m",
        "text": "Best pizza I've had in years #Foodie @localpizzeria ❤️ 😡",
        "topic": "Sports",
        "classification": "neg",
        "number_of_words": 10,
        "special_elements": 56,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@localpizzeria"],
        "mentioned_hashtags": ["#Foodie"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["❤️", "😡"],
        "no_of_likes": 52,
        "no_of_comments": 11,
        "no_of_shares": 24,
        "processed": True,
    },
    7: {
        "user_id": 1007,
        "username": "leo_n",
        "text": "Can't believe we won the match last night! #Victory @teamfans",
        "topic": "Education",
        "classification": "neg",
        "number_of_words": 10,
        "special_elements": 61,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@teamfans"],
        "mentioned_hashtags": ["#Victory"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["!"],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 309,
        "no_of_comments": 33,
        "no_of_shares": 2,
        "processed": True,
    },
    8: {
        "user_id": 1008,
        "username": "olivia_u",
        "text": "The keynote speech was inspiring #Motivation @speaker",
        "topic": "Finance",
        "classification": "pos",
        "number_of_words": 7,
        "special_elements": 53,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@speaker"],
        "mentioned_hashtags": ["#Motivation"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 498,
        "no_of_comments": 48,
        "no_of_shares": 5,
        "processed": True,
    },
    9: {
        "user_id": 1009,
        "username": "sam_a",
        "text": "Why is the internet so slow today ugh 😂 ❤️",
        "topic": "Sports",
        "classification": "neutral",
        "number_of_words": 10,
        "special_elements": 42,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["😂", "❤️"],
        "no_of_likes": 35,
        "no_of_comments": 5,
        "no_of_shares": 42,
        "processed": True,
    },
    10: {
        "user_id": 1010,
        "username": "jack_t",
        "text": "Feeling great after my morning workout #Health #Fitness",
        "topic": "Traffic",
        "classification": "pos",
        "number_of_words": 8,
        "special_elements": 55,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Health", "#Fitness"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 443,
        "no_of_comments": 12,
        "no_of_shares": 24,
        "processed": True,
    },
    11: {
        "user_id": 1011,
        "username": "olivia_u",
        "text": "Stock market crashed again today, not good news.",
        "topic": "Music",
        "classification": "neg",
        "number_of_words": 8,
        "special_elements": 48,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 83,
        "no_of_comments": 47,
        "no_of_shares": 22,
        "processed": True,
    },
    12: {
        "user_id": 1012,
        "username": "rachel_z",
        "text": "Exploring the mountains this weekend #Travel #Nature 🔥 🚀",
        "topic": "Gaming",
        "classification": "pos",
        "number_of_words": 9,
        "special_elements": 56,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Travel", "#Nature"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["🔥", "🚀"],
        "no_of_likes": 83,
        "no_of_comments": 59,
        "no_of_shares": 24,
        "processed": True,
    },
    13: {
        "user_id": 1013,
        "username": "rachel_z",
        "text": "Stock market crashed again today, not good news.",
        "topic": "Sports",
        "classification": "neutral",
        "number_of_words": 8,
        "special_elements": 48,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 166,
        "no_of_comments": 98,
        "no_of_shares": 49,
        "processed": True,
    },
    14: {
        "user_id": 1014,
        "username": "henry_p",
        "text": "This traffic is terrible today #Frustrated @citytraffic",
        "topic": "Education",
        "classification": "pos",
        "number_of_words": 7,
        "special_elements": 55,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@citytraffic"],
        "mentioned_hashtags": ["#Frustrated"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 412,
        "no_of_comments": 40,
        "no_of_shares": 25,
        "processed": True,
    },
    15: {
        "user_id": 1015,
        "username": "sam_a",
        "text": "Stock market crashed again today, not good news. 😢",
        "topic": "Weather",
        "classification": "neutral",
        "number_of_words": 9,
        "special_elements": 50,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": True,
        "emojis": ["😢"],
        "no_of_likes": 161,
        "no_of_comments": 27,
        "no_of_shares": 41,
        "processed": True,
    },
    16: {
        "user_id": 1016,
        "username": "mona_q",
        "text": "Customer service was disappointing today.",
        "topic": "Weather",
        "classification": "neutral",
        "number_of_words": 5,
        "special_elements": 41,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 234,
        "no_of_comments": 18,
        "no_of_shares": 16,
        "processed": True,
    },
    17: {
        "user_id": 1017,
        "username": "henry_p",
        "text": "The new policy announcement is confusing, honestly.",
        "topic": "Gaming",
        "classification": "neutral",
        "number_of_words": 7,
        "special_elements": 51,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 275,
        "no_of_comments": 33,
        "no_of_shares": 47,
        "processed": True,
    },
    18: {
        "user_id": 1018,
        "username": "leo_n",
        "text": "So proud of my team for this achievement #Teamwork 😂 👍",
        "topic": "Sports",
        "classification": "pos",
        "number_of_words": 11,
        "special_elements": 54,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Teamwork"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["😂", "👍"],
        "no_of_likes": 260,
        "no_of_comments": 63,
        "no_of_shares": 5,
        "processed": True,
    },
    19: {
        "user_id": 1019,
        "username": "bob_smith",
        "text": "Lost my wallet today, what a rough start #BadDay",
        "topic": "Education",
        "classification": "pos",
        "number_of_words": 9,
        "special_elements": 48,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#BadDay"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [","],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 78,
        "no_of_comments": 80,
        "no_of_shares": 10,
        "processed": True,
    },
    20: {
        "user_id": 1020,
        "username": "nick_v",
        "text": "Terrible experience with the delivery service today",
        "topic": "Movies",
        "classification": "pos",
        "number_of_words": 7,
        "special_elements": 51,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 197,
        "no_of_comments": 48,
        "no_of_shares": 38,
        "processed": True,
    },
    21: {
        "user_id": 1021,
        "username": "dave_k",
        "text": "Rain all day, so gloomy outside #Weather 😍 😀",
        "topic": "Music",
        "classification": "neutral",
        "number_of_words": 9,
        "special_elements": 44,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Weather"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [","],
        "contain_emojis": True,
        "emojis": ["😍", "😀"],
        "no_of_likes": 384,
        "no_of_comments": 34,
        "no_of_shares": 49,
        "processed": True,
    },
    22: {
        "user_id": 1022,
        "username": "karen_s",
        "text": "The sunrise this morning was absolutely breathtaking",
        "topic": "Traffic",
        "classification": "neg",
        "number_of_words": 7,
        "special_elements": 52,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 222,
        "no_of_comments": 20,
        "no_of_shares": 29,
        "processed": True,
    },
    23: {
        "user_id": 1023,
        "username": "ivy_r",
        "text": "Loving the new #AI tools! Great work @openai team",
        "topic": "Finance",
        "classification": "pos",
        "number_of_words": 9,
        "special_elements": 49,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@openai"],
        "mentioned_hashtags": ["#AI"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["!"],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 259,
        "no_of_comments": 13,
        "no_of_shares": 40,
        "processed": True,
    },
    24: {
        "user_id": 1024,
        "username": "leo_n",
        "text": "This movie was a masterpiece #MustWatch @filmcritic 🚀",
        "topic": "Fashion",
        "classification": "pos",
        "number_of_words": 8,
        "special_elements": 53,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@filmcritic"],
        "mentioned_hashtags": ["#MustWatch"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["🚀"],
        "no_of_likes": 276,
        "no_of_comments": 99,
        "no_of_shares": 33,
        "processed": True,
    },
    25: {
        "user_id": 1025,
        "username": "tina_b",
        "text": "Loving the new #AI tools! Great work @openai team",
        "topic": "Food",
        "classification": "neg",
        "number_of_words": 9,
        "special_elements": 49,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@openai"],
        "mentioned_hashtags": ["#AI"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["!"],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 9,
        "no_of_comments": 14,
        "no_of_shares": 23,
        "processed": True,
    },
    26: {
        "user_id": 1026,
        "username": "henry_p",
        "text": "This movie was a masterpiece #MustWatch @filmcritic",
        "topic": "Technology",
        "classification": "pos",
        "number_of_words": 7,
        "special_elements": 51,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@filmcritic"],
        "mentioned_hashtags": ["#MustWatch"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 449,
        "no_of_comments": 72,
        "no_of_shares": 5,
        "processed": True,
    },
    27: {
        "user_id": 1027,
        "username": "eve_m",
        "text": "Just another day, nothing special. 🔥 😍",
        "topic": "Lifestyle",
        "classification": "neutral",
        "number_of_words": 7,
        "special_elements": 38,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": True,
        "emojis": ["🔥", "😍"],
        "no_of_likes": 243,
        "no_of_comments": 70,
        "no_of_shares": 10,
        "processed": True,
    },
    28: {
        "user_id": 1028,
        "username": "quinn_y",
        "text": "Stock market crashed again today, not good news.",
        "topic": "Education",
        "classification": "neutral",
        "number_of_words": 8,
        "special_elements": 48,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 216,
        "no_of_comments": 27,
        "no_of_shares": 34,
        "processed": True,
    },
    29: {
        "user_id": 1029,
        "username": "grace_l",
        "text": "Lost my wallet today, what a rough start #BadDay",
        "topic": "Gaming",
        "classification": "neg",
        "number_of_words": 9,
        "special_elements": 48,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#BadDay"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [","],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 204,
        "no_of_comments": 85,
        "no_of_shares": 41,
        "processed": True,
    },
    30: {
        "user_id": 1030,
        "username": "dave_k",
        "text": "Finally beat the final boss #Gaming #Win 😍 🎉",
        "topic": "Sports",
        "classification": "pos",
        "number_of_words": 9,
        "special_elements": 44,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Gaming", "#Win"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["😍", "🎉"],
        "no_of_likes": 32,
        "no_of_comments": 43,
        "no_of_shares": 1,
        "processed": True,
    },
    31: {
        "user_id": 1031,
        "username": "rachel_z",
        "text": "So proud of my team for this achievement #Teamwork",
        "topic": "Sports",
        "classification": "neutral",
        "number_of_words": 9,
        "special_elements": 50,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Teamwork"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 112,
        "no_of_comments": 0,
        "no_of_shares": 4,
        "processed": True,
    },
    32: {
        "user_id": 1032,
        "username": "bob_smith",
        "text": "Just finished reading an incredible book #BookLover",
        "topic": "Sports",
        "classification": "pos",
        "number_of_words": 7,
        "special_elements": 51,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#BookLover"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 463,
        "no_of_comments": 4,
        "no_of_shares": 21,
        "processed": True,
    },
    33: {
        "user_id": 1033,
        "username": "paul_x",
        "text": "Just another day, nothing special. 😡",
        "topic": "Sports",
        "classification": "neutral",
        "number_of_words": 6,
        "special_elements": 36,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": True,
        "emojis": ["😡"],
        "no_of_likes": 67,
        "no_of_comments": 92,
        "no_of_shares": 36,
        "processed": True,
    },
    34: {
        "user_id": 1034,
        "username": "paul_x",
        "text": "So proud of my team for this achievement #Teamwork",
        "topic": "Sports",
        "classification": "neg",
        "number_of_words": 9,
        "special_elements": 50,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Teamwork"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 413,
        "no_of_comments": 52,
        "no_of_shares": 12,
        "processed": True,
    },
    35: {
        "user_id": 1035,
        "username": "dave_k",
        "text": "Can't believe we won the match last night! #Victory @teamfans",
        "topic": "Music",
        "classification": "neg",
        "number_of_words": 10,
        "special_elements": 61,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@teamfans"],
        "mentioned_hashtags": ["#Victory"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["!"],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 181,
        "no_of_comments": 54,
        "no_of_shares": 26,
        "processed": True,
    },
    36: {
        "user_id": 1036,
        "username": "bob_smith",
        "text": "Rain all day, so gloomy outside #Weather 🔥",
        "topic": "Travel",
        "classification": "neutral",
        "number_of_words": 8,
        "special_elements": 42,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Weather"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [","],
        "contain_emojis": True,
        "emojis": ["🔥"],
        "no_of_likes": 173,
        "no_of_comments": 13,
        "no_of_shares": 15,
        "processed": True,
    },
    37: {
        "user_id": 1037,
        "username": "grace_l",
        "text": "Exploring the mountains this weekend #Travel #Nature",
        "topic": "Finance",
        "classification": "neg",
        "number_of_words": 7,
        "special_elements": 52,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Travel", "#Nature"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 71,
        "no_of_comments": 54,
        "no_of_shares": 11,
        "processed": True,
    },
    38: {
        "user_id": 1038,
        "username": "olivia_u",
        "text": "Stock market crashed again today, not good news.",
        "topic": "Sports",
        "classification": "pos",
        "number_of_words": 8,
        "special_elements": 48,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 226,
        "no_of_comments": 70,
        "no_of_shares": 6,
        "processed": True,
    },
    39: {
        "user_id": 1039,
        "username": "henry_p",
        "text": "This traffic is terrible today #Frustrated @citytraffic 🔥",
        "topic": "Lifestyle",
        "classification": "neg",
        "number_of_words": 8,
        "special_elements": 57,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@citytraffic"],
        "mentioned_hashtags": ["#Frustrated"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["🔥"],
        "no_of_likes": 248,
        "no_of_comments": 61,
        "no_of_shares": 13,
        "processed": True,
    },
    40: {
        "user_id": 1040,
        "username": "bob_smith",
        "text": "Loving the autumn fashion trends this year #Style",
        "topic": "Lifestyle",
        "classification": "neg",
        "number_of_words": 8,
        "special_elements": 49,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Style"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 1,
        "no_of_comments": 49,
        "no_of_shares": 16,
        "processed": True,
    },
    41: {
        "user_id": 1041,
        "username": "jack_t",
        "text": "Rain all day, so gloomy outside #Weather",
        "topic": "Travel",
        "classification": "neutral",
        "number_of_words": 7,
        "special_elements": 40,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Weather"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [","],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 490,
        "no_of_comments": 93,
        "no_of_shares": 50,
        "processed": True,
    },
    42: {
        "user_id": 1042,
        "username": "jack_t",
        "text": "Why is the internet so slow today ugh 🚀 😢",
        "topic": "Sports",
        "classification": "pos",
        "number_of_words": 10,
        "special_elements": 41,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["🚀", "😢"],
        "no_of_likes": 296,
        "no_of_comments": 94,
        "no_of_shares": 34,
        "processed": True,
    },
    43: {
        "user_id": 1043,
        "username": "karen_s",
        "text": "This traffic is terrible today #Frustrated @citytraffic",
        "topic": "Technology",
        "classification": "pos",
        "number_of_words": 7,
        "special_elements": 55,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@citytraffic"],
        "mentioned_hashtags": ["#Frustrated"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 299,
        "no_of_comments": 61,
        "no_of_shares": 32,
        "processed": True,
    },
    44: {
        "user_id": 1044,
        "username": "frank_o",
        "text": "Had an amazing time at the concert last night!",
        "topic": "Technology",
        "classification": "neutral",
        "number_of_words": 9,
        "special_elements": 46,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["!"],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 41,
        "no_of_comments": 23,
        "no_of_shares": 4,
        "processed": True,
    },
    45: {
        "user_id": 1045,
        "username": "mona_q",
        "text": "Not sure how I feel about this update yet. 😢",
        "topic": "Traffic",
        "classification": "neutral",
        "number_of_words": 10,
        "special_elements": 44,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["."],
        "contain_emojis": True,
        "emojis": ["😢"],
        "no_of_likes": 126,
        "no_of_comments": 74,
        "no_of_shares": 38,
        "processed": True,
    },
    46: {
        "user_id": 1046,
        "username": "tina_b",
        "text": "This traffic is terrible today #Frustrated @citytraffic",
        "topic": "Traffic",
        "classification": "neg",
        "number_of_words": 7,
        "special_elements": 55,
        "contain_hashtags": True,
        "contain_mentions": True,
        "mention_persons": ["@citytraffic"],
        "mentioned_hashtags": ["#Frustrated"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 336,
        "no_of_comments": 74,
        "no_of_shares": 36,
        "processed": True,
    },
    47: {
        "user_id": 1047,
        "username": "karen_s",
        "text": "Had an amazing time at the concert last night!",
        "topic": "Weather",
        "classification": "neg",
        "number_of_words": 9,
        "special_elements": 46,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": ["!"],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 104,
        "no_of_comments": 85,
        "no_of_shares": 45,
        "processed": True,
    },
    48: {
        "user_id": 1048,
        "username": "mona_q",
        "text": "New album drop is fire #Music 😡",
        "topic": "Lifestyle",
        "classification": "neutral",
        "number_of_words": 7,
        "special_elements": 31,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Music"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": True,
        "emojis": ["😡"],
        "no_of_likes": 330,
        "no_of_comments": 38,
        "no_of_shares": 29,
        "processed": True,
    },
    49: {
        "user_id": 1049,
        "username": "carol_w",
        "text": "New album drop is fire #Music",
        "topic": "Technology",
        "classification": "neg",
        "number_of_words": 6,
        "special_elements": 29,
        "contain_hashtags": True,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": ["#Music"],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": False,
        "punctuation": [],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 318,
        "no_of_comments": 72,
        "no_of_shares": 6,
        "processed": True,
    },
    50: {
        "user_id": 1050,
        "username": "rachel_z",
        "text": "Just another day, nothing special.",
        "topic": "Sports",
        "classification": "neutral",
        "number_of_words": 5,
        "special_elements": 34,
        "contain_hashtags": False,
        "contain_mentions": False,
        "mention_persons": [],
        "mentioned_hashtags": [],
        "posted_time": "2026-07-19 03:07:41",
        "contain_punctuation": True,
        "punctuation": [",", "."],
        "contain_emojis": False,
        "emojis": [],
        "no_of_likes": 135,
        "no_of_comments": 16,
        "no_of_shares": 22,
        "processed": True,
    },
}

positive_words = [
    "good", "great", "excellent", "amazing", "awesome", "fantastic", "wonderful",
    "love", "loving", "loved", "like", "liked", "best", "happy", "joy", "excited",
    "exciting", "beautiful", "brilliant", "perfect", "nice", "cool", "fun",
    "fabulous", "delightful", "impressive", "incredible", "outstanding", "superb",
    "grateful", "thankful", "proud", "win", "winning", "won", "victory", "success",
    "successful", "positive", "recommend", "enjoy", "enjoyed", "enjoying",
    "satisfied", "satisfying", "pleased", "pleasant", "glad", "smile", "smiling",
    "cheerful", "blessed", "inspired", "inspiring", "motivated", "motivating",
    "fresh", "breathtaking", "stunning", "top", "favorite", "yay", "congratulations",
    "congrats", "hilarious", "funny", "adorable", "sweet", "kind", "helpful",
    "supportive", "encouraging", "relaxing", "peaceful", "comfortable", "smooth",
    "efficient", "reliable", "worth", "worthy", "genius", "masterpiece", "epic",
    "legendary", "flawless", "solid", "strong", "healthy", "energetic", "vibrant"
]

negative_words = [
    "bad", "terrible", "awful", "horrible", "worst", "hate", "hated", "hating",
    "dislike", "disliked", "sad", "angry", "mad", "upset", "annoyed", "annoying",
    "frustrated", "frustrating", "disappointed", "disappointing", "disgusting",
    "poor", "boring", "bored", "ugly", "nasty", "painful", "pain", "hurt",
    "hurtful", "cry", "crying", "sorry", "regret", "fail", "failed", "failure",
    "lose", "losing", "lost", "broken", "damage", "damaged", "problem",
    "problematic", "issue", "issues", "trouble", "troubling", "worried",
    "worrying", "worry", "anxious", "anxiety", "stress", "stressed", "stressful",
    "tired", "exhausted", "sick", "ill", "unfortunately", "unhappy", "negative",
    "complain", "complaint", "rude", "unfair", "cheap", "waste", "wasted",
    "slow", "confusing", "confused", "messy", "chaos", "disaster", "scary",
    "scared", "afraid", "fear", "terrifying", "gross", "weak", "useless",
    "pathetic", "shameful", "embarrassing", "embarrassed", "gloomy", "dull",
    "harsh", "cruel", "furious", "outrageous", "unacceptable", "regretful"
]

usernames= {
    1001: "alice_j",
    1002: "bob_smith",
    1003: "carol_w",
    1004: "dave_k",
    1005: "eve_m",
    1006: "frank_o",
    1007: "grace_l",
    1008: "henry_p",
    1009: "ivy_r",
    1010: "jack_t",
    1011: "karen_s",
    1012: "leo_n",
    1013: "mona_q",
    1014: "nick_v",
    1015: "olivia_u",
    1016: "paul_x",
    1017: "quinn_y",
    1018: "rachel_z",
    1019: "sam_a",
    1020: "tina_b",
    1021: "uma_c",
    1022: "victor_d",
    1023: "wendy_e",
    1024: "xavier_f",
    1025: "yasmin_g",
    1026: "zack_h",
    1027: "amber_i",
    1028: "brian_j",
    1029: "chloe_k",
    1030: "derek_l",
    1031: "ella_m",
    1032: "felix_n",
    1033: "gina_o",
    1034: "harold_p",
    1035: "isla_q",
    1036: "jasper_r",
    1037: "kayla_s",
    1038: "liam_t",
    1039: "megan_u",
    1040: "noah_v",
    1041: "priya_w",
    1042: "quincy_x",
    1043: "riley_y",
    1044: "sofia_z",
    1045: "tariq_a",
    1046: "usman_b",
    1047: "violet_c",
    1048: "will_d",
    1049: "ximena_e",
    1050: "yusuf_f"
}

topic_words = {
    "sports": [
        "cricket", "football", "soccer", "basketball", "tennis", "hockey",
        "match", "tournament", "goal", "score", "team", "player", "coach",
        "championship", "league", "referee", "stadium", "win", "victory",
        "olympics", "athlete", "training", "game", "final", "trophy"
    ],

    "food": [
        "cook", "cooking", "dishes", "recipe", "restaurant", "pizza", "burger",
        "dinner", "lunch", "breakfast", "snack", "dessert", "chef", "delicious",
        "taste", "spicy", "sweet", "menu", "cuisine", "bake", "baking",
        "grocery", "kitchen", "meal", "diet", "vegetarian", "foodie"
    ],

    "technology": [
        "ai", "tech", "software", "app", "coding", "programming", "computer",
        "gadget", "smartphone", "laptop", "robot", "internet", "startup",
        "innovation", "algorithm", "data", "cloud", "cyber", "device",
        "update", "release", "developer", "chatgpt", "machine learning"
    ],

    "travel": [
        "travel", "trip", "vacation", "flight", "hotel", "tourist", "beach",
        "mountains", "explore", "adventure", "destination", "passport",
        "backpacking", "journey", "sightseeing", "airport", "road trip",
        "camping", "resort", "holiday"
    ],

    "health": [
        "health", "fitness", "workout", "gym", "diet", "exercise", "wellness",
        "yoga", "doctor", "hospital", "medicine", "nutrition", "mental health",
        "sleep", "therapy", "healthy", "cardio", "vaccine", "disease", "checkup"
    ],

    "politics": [
        "government", "election", "policy", "president", "minister", "vote",
        "senate", "parliament", "law", "protest", "campaign", "democracy",
        "president", "law", "reform", "tax", "politician", "debate"
    ],

    "entertainment": [
        "movie", "film", "music", "album", "concert", "actor", "actress",
        "director", "show", "series", "celebrity", "trailer", "singer",
        "song", "award", "premiere", "netflix", "hollywood", "comedy"
    ],

    "finance": [
        "stock", "market", "finance", "investment", "bank", "economy", "crypto",
        "bitcoin", "trading", "shares", "profit", "loss", "budget", "loan",
        "savings", "inflation", "revenue", "salary", "tax"
    ],

    "traffic": [
        "traffic", "road", "car", "highway", "commute", "accident", "jam",
        "signal", "vehicle", "transport", "bus", "train", "parking", "route"
    ],

    "weather": [
        "weather", "rain", "sunny", "storm", "snow", "cold", "hot", "humidity",
        "forecast", "cloudy", "temperature", "wind", "climate", "flood"
    ]
}

def accessing_the_logs_files(file_name):
    try:
        with open(file_name,"r") as file:
            data = json.load(file)
    except FileNotFoundError:
        print(f"{file_name} not found")
    except json.JSONDecodeError:
        print("Data corrupted")
    else:
        print(f"{file_name} loaded successfully")

    return data


def data_saving(file_name,data,log_file):
    global files_log
    global social_posts_catalog_backup
    global message
    try:
        with open(file_name,"w",encoding="utf-8") as file:
            json.dump(data, file, indent=4, ensure_ascii=False)
    except FileExistsError:
        message = f"\"{file_name}\" already exists" 
        print(f"\"{file_name}\" already exists")
    except TypeError:
        message = f"\"{file_name}\" is not in a JSON format"
        print(f"\"{file_name}\" is not in a JSON format")
    else:
        message = f"\"{file_name}\" saved successfully"
        print(f"\"{file_name}\" saved successfully")
    finally:
        time_stamp = datetime.now().strftime('%D %H:%M:%S')
        id = int(len(log_file) + 1)
        log_file.update({id:
                            {"file_name": file_name,
                            "time_stamp": time_stamp,
                            "message": message}})

def closing_the_log_files(file_name,data):
    try:
        with open(file_name,"w") as file:
            json.dump(data, file, indent=4, ensure_ascii=False)
    except PermissionError:
        print(f"Permission for the {file_name} not granted")
    except TypeError:
        print(f"{file_name} is not in JSON format")
    else:
        print(f"{file_name} saved successfully")

if __name__ == "__main__":         
    print("\n")
    accessing_the_logs_files("files_log.JSON")

    print("\n")
    data_saving("positive_words.JSON",positive_words,files_log)

    print("\n")
    data_saving("negative_words.JSON",negative_words,files_log)

    print("\n")
    data_saving("usernames.JSON",usernames,files_log)

    print("\n")
    data_saving("topic_words.JSON",topic_words,files_log)

    print("\n")
    files_log = accessing_the_logs_files("files_log.JSON")

    print("\n")
    social_posts_catalog_backup = accessing_the_logs_files("social_posts_catalog_backup.JSON")

    print("\n")
    data_saving("social_posts_catalog.JSON",social_posts_catalog,social_posts_catalog_backup)

    print("\n")
    closing_the_log_files("social_posts_catalog_backup.JSON",social_posts_catalog_backup)